export const STORAGE_KEYS = {
  DEXCOM_USERNAME: "DEXCOM_USERNAME",
  DEXCOM_PASSWORD: "DEXCOM_PASSWORD",
  DEXCOM_SERVER: "DEXCOM_SERVER",
  DEXCOM_UNIT: "DEXCOM_UNIT",
  DEXCOM_ESTIMATED_GLUCOSE_VALUES: "DEXCOM_ESTIMATED_GLUCOSE_VALUES",
  DEXCOM_HIGH_THRESHOLD: "DEXCOM_HIGH_THRESHOLD",
  DEXCOM_LOW_THRESHOLD: "DEXCOM_LOW_THRESHOLD",
  DEXCOM_ALERT_DISMISSED: "DEXCOM_ALERT_DISMISSED",
  WEATHER_UNIT: "WEATHER_UNIT",
  WEATHER_VALUES: "WEATHER_VALUES",
}
